### ISSUE TITLE
Cursorline not visible

### ISSUE THREAD

**Issue by bilco105** [shaunsingh/nord.nvim#1]
Hi, 

Firstly, thanks so much for creating this plugin - I've been using Nord for a long time, but the lack of support for treesitter meant I had to move elsewhere, so great to be able to move back :) 

Just a question, not necessarily a bug. At the moment, cursorline is currently set to `nord.none`, so isn't visible. On the original vim plugin, it's set to `nord1_gui` (https://github.com/arcticicestudio/nord-vim/blob/5867535cea7bb6b4c219fa0726c93e4b055debd2/colors/nord.vim#L170)

However, on the original plugin, colorcolumn & cursorline conflicted as they were both using `nord1_gui`. As you're using `nord.active ` for colorcolumn, this means that we could use `nord.nord1_gui` and support both features.

Was it an intentional decision to have cursorline invisible, or would it be possible to have it changed to nord1_gui?

Thanks!

**Comment by shaunsingh** [comment]
Hi, thanks for bringing this up!

When I was designing this theme I originally purposely made the cursor line transparent since I thought it looked cleaner that way. However that was before the decision to make it public, I think I'll add a variable and make the option available to the user 

For now, can you test this branch? https://github.com/shaunsingh/nord.nvim/tree/cursorline, it includes `nord1_gui` as the cursor line color

**Comment by shaunsingh** [comment]
Closing as the cursorline changes were merged to master
