### ISSUE TITLE
Vimdiff Whitespace Highlighting

### ISSUE THREAD

**Issue by austinliuigi** [shaunsingh/nord.nvim#106]
For some reason, it seems like vimdiff highlighting is a bit buggy. I tested it with the tokyonight colorscheme to make sure it wasn't an issue with neovim itself, but tokyonight seems to have no problem with it.

Tokyonight:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/186078500-8aeedbfa-2e61-453c-939d-cc5b79e410e5.png">

Nord:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/186078433-bb27212e-ba61-4145-aa40-50e04e36923a.png">

**Comment by antoineco** [comment]
@austinliuigi are you referring to the aggressive background colors or to the listchars (e.g. end-of-line marker) which are highlighted with a black background?

The former can be easily tweaked by using `nord1` as background color for diffs instead of this reverse effect:

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/3299086/187297636-9cdbc572-bccc-407d-9533-c4a725f7bc3c.png">

Incidentally, this also makes listchars blend better with the background (I deliberately changed their colors to `nord9` here to make them stand out in the screenshot, but the default is also `nord1`).

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/3299086/187299559-f0c2f1fb-64c1-43bc-800e-5e067d8e042e.png">


I'm happy to send a PR with a suggestion to make it the default if you like what I just showed.

**Comment by shaunsingh** [comment]
Looks great, a pr would be wonderful

**Comment by antoineco** [comment]
@shaunsingh @austinliuigi actually a PR won't be necessary. I just realized this theme already supports `let g:nord_uniform_diff_background = 1`, just like the official Vim theme.

Use this in your `init.lua` and you're good to go:

```lua
vim.g.nord_uniform_diff_background = true
```
