### ISSUE TITLE
YAML not working propoerly

### ISSUE THREAD

**Issue by ygworldr** [shaunsingh/nord.nvim#14]
After some debugging, I found that the current theme does not work on YAML files.

Using the normal nord (no treesitter) theme:
![screenshop1](https://user-images.githubusercontent.com/62601401/121916792-6152bf00-cd2c-11eb-8470-eb25fcfd6074.png)

Using the normal nord (no treesitter) theme:

With `nord.vim`:
![screenshop2](https://user-images.githubusercontent.com/62601401/121916796-61eb5580-cd2c-11eb-91b2-ed8c8839d995.png)

Am I doing something wrong there?

**Comment by shaunsingh** [comment]
The theme is actually working as expected, its just that the treesitter parser for yaml isn't very colorful. You can open an issue at https://github.com/ikatyang/tree-sitter-yaml. If they don't respond and/or close your issue, then I'll be happy to make a language configuration for yaml so it looks a bit better 

An alternative would be to uninstall treesitter-yaml so that it falls back to the regex highlighting, which may not be as accurate but would look better.

**Comment by ygworldr** [comment]
Oh my god! That's … really not what I was expecting. Thank you, as always you are super helpful! In the first instance, I shall open an issue upstream and link this one.

In case anyone wanted to know more, here's my Lua config for tree sitter:

```vim
" Tree sitter.
" -▼-
:lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,  -- false will disable the whole extension
    disable = {"yaml", },  -- list of language that will be disabled
    -- disable = {},  -- list of language that will be disabled
  },
}
EOF
" -▲-
```

**Comment by ygworldr** [comment]
[Linked upstream issue](https://github.com/ikatyang/tree-sitter-yaml/issues/28)
