### ISSUE TITLE
Treesitter support in vim-nord -- link FYI

### ISSUE THREAD

**Issue by kierun** [shaunsingh/nord.nvim#3]
[Nord has an issue/PR for tree sitter support](https://github.com/arcticicestudio/nord-vim/issues/235#issuecomment-842303916).

This might be of interest and I have linked this repo to the issue there.

Feel free to close this if it is of no interest. ^_^

**Comment by shaunsingh** [comment]
Thanks for bringing that to my attention! Nice to see tree sitter being integrated into the main color-scheme. For now I will leave the issue open

The biggest issue is that Nord.nvim isn't backwards compatible with vim8,  since it's written in lua. For now I've opened this issue in the main repository,https://github.com/arcticicestudio/nord/issues/157

**Comment by kierun** [comment]
You are most welcome! :grinning: Thank you for doing this. I'll install it when I have some time -- then, I will need to figure out how to change the background to black and keep the rest the same. :+1:

**Comment by shaunsingh** [comment]
Thanks for the feedback! If you would like to change the background to black, you can fork the repository, then go to this file: https://github.com/shaunsingh/nord.nvim/blob/master/lua/nord/colors.lua, and edit the `bg` and `bg_alt` colors to match your taste

Enjoy!

**Comment by kierun** [comment]
Thank you! I might just have a branch and keep your changes merged in whenever Plug updates.

How hard would it be to add a option in `vimrc`? Never done it but always willing to learn ^_-

**Comment by shaunsingh** [comment]
Would that be an option to switch between branches with vim-plug, or an option to change the background color?

A Background color switch would be a quick easy addition to the theme, but I would prefer not to add it on the main branch since I personally feel change the background color detracts from the feel of the theme.

**Comment by kierun** [comment]
> A Background color switch would be a quick easy addition to the theme, but I would prefer not to add it on the main branch since I personally feel change the background color detracts from the feel of the theme.

This one. And it is a very reasonable thing to do! :+1: Thank you.

**Comment by shaunsingh** [comment]
I talked a tad bit with articicestudios about adding the nord theme or improving treesitter support, I'll go from there. Thanks once again for bringing this to my attention!

**Comment by kierun** [comment]
You are most welcome.
