### ISSUE TITLE
airline-vim Nord theme colours

### ISSUE THREAD

**Issue by kierun** [shaunsingh/nord.nvim#4]
![screenshot1](https://user-images.githubusercontent.com/3079575/118497199-c232ab80-b71c-11eb-976f-3a71edfcada0.png)

The above is using `nord-vim` with airline-vim's nord theme.

![screenshot2](https://user-images.githubusercontent.com/3079575/118497203-c2cb4200-b71c-11eb-91cf-b4e18459cbea.png)

This is what I see using your code.

Note: please do ignore the background colour, I changed it to match my weird and abject tastes.

**Comment by shaunsingh** [comment]
At the moment, Nord.nvim does not provide a vim-airline theme, mainly since it is a neovim/lua theme and I feel like having a vimscript airline theme would go against that. 

However, if you don't mind doing a bit of configuration, we do have a [lualine](https://github.com/hoob3rt/lualine.nvim) theme. 

If you prefer to stick to airline, you can use both the nord-vim and Nord.nvim themes at the same time, and load Nord.nvim through the following line: 

```
lua <<EOF
require('nord').set()
--any other lua configuration 
EOF
```

Then set the airline theme like normal. It might add a slight amount of startup time (probably 3-4 ms since you're loading two themes instead of just one), but should work as expected. 

Let me know if you need anything else

**Comment by kierun** [comment]
… I was just looking at [lualine](https://github.com/hoob3rt/lualine.nvim) and it might be time for an update…

**Comment by shaunsingh** [comment]
Yup, lualine is a very nice piece of kit. Just configure the theme through the following line 

```lua
require('lualine').setup {
  options = {
    -- ... your lualine config
    theme = 'nord'
    -- ... your lualine config
  }
}
```

and to match your current config, change the separators to triangles. Good luck!

**Comment by kierun** [comment]
Awesome! Your helpfullness is much appreciate. Thank you.

I switched to `lualine` and `nord.nvim`. It was painless.
